### ISSUE TITLE
Windows wallet and node require elevated privileges

### ISSUE THREAD

**Issue by cryptonoob42** [hclivess/Bismuth#269]
The windows wallet and the Windows node require elevated privileges. This appears unnecessary and might pose a security risk. Both applications should be able to run with regular privileges.

**Comment by EggPool** [comment]
Do we know what triggers that elevation request?

Is it due to the py-installer process, or to some specific python code?

**Comment by cryptonoob42** [comment]
On the machine where I installed it (Windows 7, installed via Bismuth_installer.exe) the start menu entries for node and wallet have the little shield icon, in other words "Run as administrator" is checked in the menu entries' "compatibility" properties. I assume that the installer has configured the shortcuts that way. I have not (yet) tried running the applications without admin permissions, so I cannot say whether or not they work without elevated privileges.

**Comment by cryptonoob42** [comment]
As I see, it is indeed done by the installer, see https://github.com/hclivess/Bismuth/blob/master/setup.iss#L34 and the following lines.

**Comment by cryptonoob42** [comment]
I've tried to run wallet.exe as a regular user. I'm asked for elevated privileges nonetheless, probably due to the registry entries.

**Comment by hclivess** [comment]
If it does not ask, it crashes. Windows works like that, sadly.

**Comment by EggPool** [comment]
Means something requires them. Question is, what does?
is this some python code we could fond a workaround for, or an installer config or option that can be avoided?

**Comment by hclivess** [comment]
I feel skeptical about this, all executalbes in Windows require Microsoft-approved signatures or elevated privileges in order to run, especially in the last 3 years or so. They are heading the Apple way.

**Comment by psipherious** [comment]
Not a single wallet from any other cryptocurrency that I currently use require admin privileges to run (at least 10 wallets currently and have used many over the years).

I can't say whether they all go through any sort of process to get things signed by Microsoft or if there is some type of automated method of having signed software.

The large majority don't ask me "are you sure you wish to run this potentially unsafe software". Requiring admin privileges most certainly poses a security risk as cryptonoob42 has suggested.

I wonder if perhaps Windows users can get instructions to execute the node/wallets using python command line directly from the source? or is this not possible? Does it have to be compiled to binary to function?

I notice this issue was only opened less than a week ago, is this a new problem only in most recent versions of Bismuth or has it always been this way? (I am new to Bismuth)

**Comment by EggPool** [comment]
You can install python, pip install dependencies on your window machine and run from source.

The installer just packages the python as bytecode and interfaces with windows to create the icons and such.
I don't know what exactly causes the requirement for elevated privileges.
As for my miner, it's also build with pyinstaller, but not automatic install.
Another difference is that the node needs to open a tcp server, could need more privileges than 'just' a miner.
If you find the cause and a way not to require those elevation, you're welcome!
It's not a new issue, it's been that way since a long time iirc.

**Comment by hclivess** [comment]
Earlier, the node would just not start without being run as administrator. This is more straightforward.

**Comment by hclivess** [comment]
This is fixed in the installer (script bundled)
