### ISSUE TITLE
'./Crypto' out of date implementation

### ISSUE THREAD

**Issue by Aareon** [hclivess/Bismuth#278]
All usages of `Crypto` should be replaced with `Cryptodome` from the `pycryptodomex` module. I've tested in my own environment and everything is still functional
```
Windows 10
Python 3.6.5
```

**Comment by EggPool** [comment]
We are aware.
Current requirement is "pycryptodome" module, that exports a "pycrypto" interface for compatibility, but it's supposed to be the same code inside. 
Only drawback if the conflict if some user also installs outdated PyCrypto.

We will surely move to pycryptodomex later on when refactoring, after extensive testing on huge test cases, because the crypto functions are very sensitive and a very very little difference can mean losing a wallet.

**Comment by hclivess** [comment]
Cryptodome without x at the end is a drop in replacement for Crypto (pycrypto)

**Comment by hclivess** [comment]
Replaced anyway
