### ISSUE TITLE
Move data to HDD on time basis instead of after every sync batch

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#301]
Consider

**Comment by Aareon** [comment]
Keeping the data in memory could cause some undesired slow downs. Depending on the current average time between sync batches, I think this would be a good idea.

**Comment by hclivess** [comment]
Data is normally accessed from the memory (from compressed hyper.db moved to RAM at the beginning of the process). However, dumping data to HDD takes some time and slows down the sync process.

**Comment by Aareon** [comment]
That’s very true, but I’m unclear as to how long the dump typically takes in a normal setup. We could possibly put it on a timer and event-based setup. So that if there’s a sync batch every 10 minutes (for example), then we don’t dump. But if within 10 minutes there’s no ready sync batch, we go ahead and dump what we have.

**Comment by hclivess** [comment]
There are architectural concerns with this, would probably be done in a complete node rewrite. Not critical by any means.
